DROP table IF EXISTS endpointhit cascade;

CREATE TABLE IF NOT EXISTS endpointhit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(100)                            NOT NULL,
    uri       VARCHAR(100)                            NOT NULL,
    ip        VARCHAR(40)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_endpointhit PRIMARY KEY (id)
);